name: Manual Run of Item Shop Generator

on:
  workflow_dispatch: # Это событие позволяет запускать workflow вручную через GitHub интерфейс
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # Убедитесь, что версия Node.js совпадает с той, что требуется вашим проектом

    - name: Install dependencies
      run: npm install

    - name: Verify secrets
      run: |
        if [ -z "${{ secrets.FNAPI_IO_TOKEN }}" ]; then
          echo "Error: FNAPI_IO_TOKEN is not set"
          exit 1
        fi
        if [ -z "${{ secrets.IMGBB_API_KEY }}" ]; then
          echo "Error: IMGBB_API_KEY is not set"
          exit 1
        fi
        if [ -z "${{ secrets.TELEGRAM_BOT_TOKEN }}" ]; then
          echo "Error: TELEGRAM_BOT_TOKEN is not set"
          exit 1
        fi
        if [ -z "${{ secrets.TELEGRAM_CHAT_ID }}" ]; then
          echo "Error: TELEGRAM_CHAT_ID is not set"
          exit 1
        fi
        
    - name: Run script and extract image URL
      id: run_script
      env:
        FNAPI_IO_TOKEN: ${{ secrets.FNAPI_IO_TOKEN }}
        IMGBB_API_KEY: ${{ secrets.IMGBB_API_KEY }}
      run: |
        IMAGE_URL=$(node index_fnapi.io.js | tail -n 1)
        IMAGE_URL=$(echo $IMAGE_URL | xargs) # Remove leading/trailing spaces/newlines
        
        if [[ ! "$IMAGE_URL" =~ ^https?:// ]]; then
          echo "Error: IMAGE_URL is invalid or empty. Skipping further steps."
          exit 1
        fi
        echo "IMAGE_URL=$IMAGE_URL" >> $GITHUB_ENV

    - name: Send Image URL to Make.com Webhook
      env:
        MAKE_WEBHOOK_URL: ${{ secrets.MAKE_WEBHOOK_URL }}
      run: |
        if [[ ! "$IMAGE_URL" =~ ^https?:// ]]; then
          echo "Error: IMAGE_URL is invalid or empty. Skipping Make.com notification."
          exit 1
        fi
        echo "Sending Image URL: $IMAGE_URL to Make.com Webhook"
        curl -s -X POST "$MAKE_WEBHOOK_URL" -H "Content-Type: application/json" -d '{"imageUrl": "$IMAGE_URL"}'
        
        
    
