name: Manual Run of Item Shop Generator

on:
  workflow_dispatch: # Это событие позволяет запускать workflow вручную через GitHub интерфейс
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # Убедитесь, что версия Node.js совпадает с той, что требуется вашим проектом

    - name: Install dependencies
      run: npm install
      
    - name: Run script and extract image URL
      env:
        FNAPI_IO_TOKEN: ${{ secrets.FNAPI_IO_TOKEN }}
        IMGBB_API_KEY: ${{ secrets.IMGBB_API_KEY }}
      run: |
        IMAGE_URL=$(node index_fnapi.io.js | tail -n 1)
        if [[ ! "$IMAGE_URL" =~ ^https?:// ]]; then
          echo "Error: IMAGE_URL is invalid or empty. Skipping further steps."
          exit 1
        fi
        echo "IMAGE_URL=$IMAGE_URL" >> $GITHUB_ENV

    - name: Send Image to Telegram Bot
      if: env.IMAGE_URL != ''
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        IMAGE_URL: ${{ env.IMAGE_URL }}
      run: |
        curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendPhoto" \
          -F chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -F photo="$IMAGE_URL"
          
        
